"""License information shown in Help ▸ About and shipped with the executable.

``notices()`` lists the bundled components with their licenses and license texts. The build
writes it to ``THIRD_PARTY_NOTICES.txt`` inside the executable (``scripts/build_exe.py``);
from a source checkout it is generated from the installed distributions.
"""

from __future__ import annotations

import importlib.metadata as md
import re
from typing import Any

from pdfeditor import SOURCE_URL, __version__
from pdfeditor.bundle import data_path

NOTICES_FILE = "THIRD_PARTY_NOTICES.txt"
LICENSE_FILE = "LICENSE"
# Python distributions that are build/test tools or excluded from the executable.
_NOT_BUNDLED = {"numpy", "tomli"}
# Components compiled into the bundled distributions, which have no metadata of their own.
_EMBEDDED = (
    ("MuPDF (in PyMuPDF)", "AGPL-3.0-or-later", "https://mupdf.com"),
    ("Tesseract OCR engine (in MuPDF)", "Apache-2.0", "https://github.com/tesseract-ocr/tesseract"),
    ("Tesseract English data (tessdata_fast)", "Apache-2.0", "https://github.com/tesseract-ocr/tessdata_fast"),
    ("Qt 6 (in PySide6)", "LGPL-3.0-only", "https://www.qt.io/licensing"),
    ("qpdf (in pikepdf)", "Apache-2.0", "https://github.com/qpdf/qpdf"),
    ("Python", "PSF-2.0", "https://docs.python.org/3/license.html"),
    ("sRGB colour profile", "generated by Little CMS (MIT) via Pillow", "https://www.littlecms.com"),
)  # fmt: skip


def about_text() -> str:
    return (
        f"pdfeditor {__version__}\n"
        "Copyright the pdfeditor authors.\n\n"
        "This program is free software: you can redistribute it and/or modify it under the "
        "terms of the GNU Affero General Public License as published by the Free Software "
        "Foundation, either version 3 of the License, or (at your option) any later version. "
        "It is distributed WITHOUT ANY WARRANTY; see the license for details.\n\n"
        f"Complete corresponding source code: {SOURCE_URL}\n"
        "If you received this program without the source, you can request it from whoever "
        "gave it to you; they must provide it under the terms of the AGPL."
    )


def _runtime_distributions() -> list[md.Distribution]:
    seen: dict[str, md.Distribution] = {}

    def walk(name: str) -> None:
        try:
            dist = md.distribution(name)
        except md.PackageNotFoundError:
            return
        for req in dist.requires or []:
            if "extra ==" in req:
                continue
            dep = re.split(r"[ ;<>=!~\[(]", req, maxsplit=1)[0]
            key = dep.lower().replace("_", "-")
            if key in seen or key in _NOT_BUNDLED:
                continue
            try:
                seen[key] = md.distribution(dep)
            except md.PackageNotFoundError:
                continue
            walk(dep)

    walk("pdfeditor")
    return sorted(seen.values(), key=lambda d: d.metadata["Name"].lower())


def _license_of(dist: md.Distribution) -> str:
    meta: Any = dist.metadata  # email.Message-like; typeshed's PackageMetadata is narrower
    expression = meta.get("License-Expression")
    if expression:
        return expression
    text = (meta.get("License") or "").strip()
    if text and "\n" not in text and len(text) < 100:
        return text
    classifiers = [c.split("::")[-1].strip() for c in meta.get_all("Classifier") or []]
    return ", ".join(c for c in classifiers if "License" in c or "GPL" in c) or "see license text"


def _license_texts(dist: md.Distribution) -> list[str]:
    texts = []
    for f in dist.files or []:
        if re.search(r"(LICEN[CS]E|COPYING|NOTICE)", f.name, re.IGNORECASE):
            try:
                texts.append(f.read_binary().decode("utf-8", errors="replace").strip())
            except (OSError, ValueError):
                continue
    return texts


def build_notices() -> str:
    """The notices text from the installed distributions (source checkout / build time)."""
    lines = [f"pdfeditor {__version__} — third-party components", "=" * 60, ""]
    for dist in _runtime_distributions():
        meta: Any = dist.metadata
        lines.append(f"{meta['Name']} {dist.version} — {_license_of(dist)}")
        home = meta.get("Home-page") or next(
            (u.split(",", 1)[1].strip() for u in meta.get_all("Project-URL") or []), ""
        )
        if home:
            lines.append(f"  {home}")
    lines.append("")
    lines.append("Included inside the components above:")
    for name, license_, url in _EMBEDDED:
        lines.append(f"{name} — {license_}  {url}")
    lines += ["", "", "License texts", "=" * 60]
    for dist in _runtime_distributions():
        for text in _license_texts(dist):
            lines += ["", f"--- {dist.metadata['Name']} ---", text]
    return "\n".join(lines) + "\n"


def notices() -> str:
    """Bundled notices in the executable, else generated from the installed packages."""
    try:
        return data_path(NOTICES_FILE).read_text(encoding="utf-8")
    except FileNotFoundError:
        return build_notices()


def license_text() -> str:
    try:
        return data_path(LICENSE_FILE).read_text(encoding="utf-8")
    except FileNotFoundError:
        from pathlib import Path

        repo = Path(__file__).resolve().parents[2] / "LICENSE"
        return repo.read_text(encoding="utf-8") if repo.exists() else ""
